version: '3.8'

services:

  dev_db:
    container_name: ftf_postgres_dev
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev

  test_db:
    container_name: ftf_postgres_test
    image: postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080