"""add auth

Revision ID: 1f13e30baf24
Revises: 0258f997694a
Create Date: 2020-04-19 11:14:48.266842

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1f13e30baf24"
down_revision = "0258f997694a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=64), nullable=True))
    op.add_column(
        "users", sa.Column("password_hash", sa.String(length=128), nullable=True)
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
