"""add subscription

Revision ID: 25d57431da60
Revises: 4001858848e3
Create Date: 2020-04-29 09:05:37.638048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "25d57431da60"
down_revision = "4001858848e3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("subscribed", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "subscribed")
    # ### end Alembic commands ###
