"""empty message

Revision ID: 4001858848e3
Revises: 55d41ea5331e
Create Date: 2020-04-28 08:24:16.796489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4001858848e3"
down_revision = "55d41ea5331e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("about_me", sa.Text(), nullable=True))
    op.add_column(
        "users", sa.Column("avatar_hash", sa.String(length=32), nullable=True)
    )
    op.add_column("users", sa.Column("favorite_genres", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("first_artist_forever", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("last_seen", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("location", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("member_since", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("name", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("second_artist_forever", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "second_artist_forever")
    op.drop_column("users", "name")
    op.drop_column("users", "member_since")
    op.drop_column("users", "location")
    op.drop_column("users", "last_seen")
    op.drop_column("users", "first_artist_forever")
    op.drop_column("users", "favorite_genres")
    op.drop_column("users", "avatar_hash")
    op.drop_column("users", "about_me")
    # ### end Alembic commands ###
