"""add user roles/perissions

Revision ID: 55d41ea5331e
Revises: e05b841e151c
Create Date: 2020-04-27 09:21:03.335607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "55d41ea5331e"
down_revision = "e05b841e151c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("default", sa.Boolean(), nullable=True))
    op.add_column("roles", sa.Column("permissions", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_roles_default"), "roles", ["default"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_roles_default"), table_name="roles")
    op.drop_column("roles", "permissions")
    op.drop_column("roles", "default")
    # ### end Alembic commands ###
