---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ftf-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: default-token-t9v8q
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ftf-config-map
data:
  FLASK_CONFIG: "prod"
  FLASK_ENV: "production"
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: ftf-ingress
spec:
  rules:
    - host: stg.4trackfriday.com
      http:
        paths:
          - backend:
              serviceName: ftf-service
              servicePort: 8080