---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ftf-deployment
spec:
  replicas: 0
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: ftf-web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      imagePullSecrets:
        - name: ftf-secret
      containers:
        - name: ftf-web-app
          image: "gcr.io/four-track-friday-2/ftf_web_app"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: ftf-secret
            - configMapRef:
                name: ftf-config-map
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 60
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 60
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 1m
              memory: 64Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always