---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ftf-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ftf-ip
    networking.gke.io/managed-certificates: ftf-cert
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: ftf-service
    servicePort: 8080