---
apiVersion: v1
kind: Secret
metadata:
  name: ftf-secret
  labels:
    app: ftf-web-app
type: Opaque
data:
  # use the one in src/k8s/dev for localhost
  # use the one in src/k8s/stg for GCP staging
  # use the one in src/k8s/prod for GCP production