# 0) https://cloud.google.com/sql/docs/postgres/connect-kubernetes-engine#proxy-with-service-account-key
# 1) kubectl apply -f service-account.yaml
# 2)
#  gcloud iam service-accounts add-iam-policy-binding \
#  --role roles/iam.workloadIdentityUser \
#  --member "serviceAccount:<YOUR-GCP-PROJECT>.svc.id.goog[<YOUR-K8S-NAMESPACE>/<YOUR-KSA-NAME>]" \
#  <YOUR-GSA-NAME>@<YOUR-GCP-PROJECT>.iam.gserviceaccount.com
#
# 3)
#  kubectl annotate serviceaccount \
#  <YOUR-KSA-NAME> \
#  iam.gke.io/gcp-service-account=<YOUR-GSA-NAME>@<YOUR-GCP-PROJECT>.iam.gserviceaccount.com